FOS\UserBundle\Model\User:    
    exclusion_policy: ALL
    group: user
    properties:
        id:
            expose: true
        username:
            expose: true
        email:
            expose: true
        enabled:
            expose: true
        last_login:
            expose: true