register:
    path:     /register
    defaults: { _controller: AppBundle:User:register }


profile:
    path:     /profile/{id}
    defaults: { _controller: AppBundle:User:profile }
    methods:    [GET]

edit:
    path:     /edit
    defaults: { _controller: AppBundle:User:edit }

delete:
    path:     /delete
    defaults: { _controller: AppBundle:User:delete }

login:
    path:     /login
    defaults: { _controller: AppBundle:Login:login }
